### ISSUE TITLE
A vista nao se modifica

### ISSUE THREAD

**Issue by mare-soria** [adelgado/fullpage-rails#3]
Olá! estou testando esta gem mas nao está funcionando corretamente... o script carrega bem mas a vista nao se modifica, alguma ideia de que pode estar acontecendo?
Tenho usado o fullpage em outros entornos de desenvolvimento sem problemas.

**Comment by adelgado** [comment]
@MareSoria Ol&aacute;! 6 anos de GitHub e finalmente uma Issue em portugu&ecirc;s :-)

H&aacute; algum erro no Console de JavaScript? Voc&ecirc; consegue reproduzir o problema num projeto Rails virgem?

**Comment by mare-soria** [comment]
@adelgado Uoou, que emoção ser a primeira :) mesmo assim sou gringa, o meu português é limitado, então nao se emociona muito nao.

Olha, eu estou me iniciando em Rails na verdade, mas to achando que o archivo do style nao está se carregando, a gem inclui ele né? No console tá todo certo, nenhum erro.
O projeto é virgem sim, estou no inicio do desenvolvimento.
Lí por ai que o turbolinks pode estar complicando as coisas também, o que você acha?

**Comment by adelgado** [comment]
@MareSoria A gem inclui o arquivos de estilo [aqui](https://github.com/adelgado/fullpage-rails/blob/master/vendor/assets/stylesheets/jquery.fullpage.css), mas você que tem que carregá-lo via Asset Pipeline.

Qual versão de Rails você está usando?

**Comment by mare-soria** [comment]
@adelgado Estou usando Rails 5. 
Então posso chamar o archivo com um require? ou com um @import ou com um tag_link?

**Comment by mare-soria** [comment]
@adelgado 
Pronto, ta funcionando!
Valeu valeu pelo soporte... e pela Gem! 
Um abraço

**Comment by adelgado** [comment]
@MareSoria Beleza, bom saber. Abraço!
